<a href="https://colab.research.google.com/github/GildasTaliah/Solutions_with_PyNoteBook/blob/main/NumpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRO

**NumPy**, short for **Numerical Python**, is a package to perform scientific computing in Python efficaciously. It includes but not limited to: random number generation capabilities, functions for mathematical and statiscal operations and much more.

In [ ]:
# Install
"Remove '#' to install"
#pip! install numpy

"Remove '#' to install"

In [ ]:
# import numpy package
import numpy as np

# NumPy Arrays
Numpy arrays are good replacements for python list, for the allow efficient array operations.

Below we compute put call parity ratio using: Put and Call options volume

In [ ]:
# puts
put_l = list([29, 59.01, 87.21, 129.03, 50.55])

# coreeponding calls
call_l = [89, 13.01, 67.21, 149.03, 49.55 ]

# Compute Put Call Parity
put_l/call_l

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
put, call = np.array(put_l), np.array(call_l)
pcr = put/call
pcr

array([0.3258427 , 4.53574174, 1.29757477, 0.86579883, 1.02018163])

In [ ]:
# Addition
print(put_l + call_l)    # Can add list, but just appending
print(put + call)

# Subtraction
#print(put_l - call_l).  # Can't subtract list element
print(put - call)

# Multiplication
#print(put_l * call_l).  # Can't multiply list element
print(put * call)

# Division
#print(put_l / call_l).  # Can't Divide list
print(put / call)

[29, 59.01, 87.21, 129.03, 50.55, 89, 13.01, 67.21, 149.03, 49.55]
[118.    72.02 154.42 278.06 100.1 ]
[-60.  46.  20. -20.   1.]
[ 2581.       767.7201  5861.3841 19229.3409  2504.7525]
[0.3258427  4.53574174 1.29757477 0.86579883 1.02018163]


# Checking Arrays

In [ ]:
type(put)

numpy.ndarray

In [ ]:
type(np.array([put, call]))

numpy.ndarray

|-|-|
|-|-|
|Text Type:	| str|
|-|-|
|Numeric Types:	|int, float, complex|
|Sequence Types:	|list, tuple, range|
|Mapping Type:|	dict|
|Set Types:	|set, frozenset|
|Boolean Type:	|bool|
|Binary Types:	|bytes, bytearray, memoryview|
|-|-|
|None Type:	|NoneType|
|-|-|


In [ ]:
## Data types
np.array([5.01, 'Python Solutions', 2, True, 'Continets', False])

array(['5.01', 'Python Solutions', '2', 'True', 'Continets', 'False'],
      dtype='<U32')

In [ ]:
for ele in np.array([5.01, 'Python Solutions', 2, True, 'Continets']):
    print(type(ele))

for ele in np.array([5.01, 4, 3.78, 2]):
    print(ele.dtype)

for ele in np.array([5, 4, 2, 3]):
    print(type(ele))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
float64
float64
float64
float64
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Random Numbers

In [ ]:
# Random number between 0 and 1, with random.rand function from numpy

# single
print(np.random.rand(), '\n')

# 1-d
print(np.random.rand(5))
# 2-d
print(np.random.rand(2, 3))
print()

# Generate ranndom interval between 0 and 6.
print(np.random.randint(6))
# Generate ranndom interval between 0 and 6.
print(np.random.randint(6, 10))
# Generate ranndom interval between 0 and 6. 1-d
print(np.random.randint(6, 10, 5))
# Generate ranndom interval between 0 and 6. 2-d
print(np.random.randint(6, 10, (2, 3)))


# Generate random float
print()
print(np.random.random())
# Generate random float. 1-d
print(np.random.random(5))
# Generate random float. 2-d
print(np.random.random((2, 3)))

# Generate intergers between 100 and 120
print()
print(np.random.randint(100, 120))
# Generate intergers. 1-d
print(np.random.randint(100, size=5))
# Generate intergers. 2-d
print(np.random.randint(100, size=(2, 3)))

0.40889863683415706 

[0.95077179 0.54322487 0.36559624 0.57453689 0.68976233]
[[0.32430284 0.45068109 0.15734899]
 [0.83212898 0.79860915 0.08890259]]

4
8
[9 6 6 9 6]
[[8 9 7]
 [8 9 6]]

0.3084777352810649
[0.61567972 0.72241126 0.94258006 0.59398729 0.32597384]
[[0.01414453 0.56207471 0.85787076]
 [0.9633898  0.42186184 0.75792486]]

119
[20  1 63 92 43]
[[22 76 19]
 [31 54 60]]


# Array Creation

In [ ]:
# Create 1-d array of zeros
print(np.zeros(5))
print(np.zeros(5, dtype=int))

# Create 2-d array of zeros
print(np.zeros((2, 3), '\n'))


# create 1-d array of ones
print(np.ones(5))
print(np.ones(5, dtype=int))

# Create 2-d array of ones
print(np.ones((2, 3)), '\n')

# Create a 1-dimensional array with value as 75
print(np.full(5, 75))

# Create a two-dimensional array with value as 55
print(np.full((2, 3), 55))

# Create an array with only stop argument
print(np.arange(5) )

# Create an array with intervals and step value as 0.5
print(np.arange(24.25, 41, 0.75), '\n')

# Create evenly spaced array with 10 numbers within interval -5 to 10
np.linspace(-5, 10, num=10)

# Creat an array excluding end value
np.linspace(2.0, 3.0, num=5, endpoint=False)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]] 

[75 75 75 75 75]
[[55 55 55]
 [55 55 55]]
[0 1 2 3 4]
[24.25 25.   25.75 26.5  27.25 28.   28.75 29.5  30.25 31.   31.75 32.5
 33.25 34.   34.75 35.5  36.25 37.   37.75 38.5  39.25 40.   40.75] 



array([2. , 2.2, 2.4, 2.6, 2.8])

# Prob Distributions

In [ ]:
# Generate random numbers from a standard normal normal distribution
num = [np.random.randn() for _ in range(10)]
print(np.round(num,4))

# Generate a 2-dimensional array over N(0, 1)
norm = np.random.randn(5, 2)
print(norm)
norm.T

[ 0.743   0.8638 -0.2321 -0.3538 -0.1382 -0.5687  0.1328 -0.0886 -0.6696
 -0.0922]
[[ 2.15213433 -1.62309421]
 [ 0.02583727  1.15048094]
 [-0.219447    1.47539779]
 [ 0.34993881  0.20444893]
 [ 0.76039088  0.60932799]]


array([[ 2.15213433,  0.02583727, -0.219447  ,  0.34993881,  0.76039088],
       [-1.62309421,  1.15048094,  1.47539779,  0.20444893,  0.60932799]])

In [ ]:
# Binomial Dist
# Number of trials, probability of each trial
n, p = 1, 0.5

# Flip a coin once and repeat  50 times
samples = np.random.binomial(n, p, 50)

# How many heads(1), from that ?
print('For each trial of one', samples)
print(np.sum(samples))

# Flip a coin 5 times, and repeat  50 times
n = 5
samples = np.random.binomial(n, p, 50)

print('For each trial of five', samples)
print(np.sum(samples))
# Average head from each of the 50 times
print(np.mean(samples))

For each trial of one [0 1 0 1 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1
 0 1 1 1 0 1 0 0 1 1 0 1 0]
31
For each trial of five [3 0 3 4 4 1 2 3 2 5 5 3 3 1 3 1 4 2 2 5 2 2 3 3 0 3 4 4 4 4 1 3 3 3 3 3 1
 2 2 1 2 2 2 3 4 3 5 3 2 2]
135
2.7


# Array Attributes and Methods

In [ ]:
# check dimensions
print(samples, '\n')
print('Number of dim', samples.ndim)
print('Shape', samples.shape)
print('Size', samples.size)
print('Data type', samples.dtype, '\n')


print(norm, '\n')
print('Number of dim', norm.ndim)
print('Shape', norm.shape)
print(norm.T.shape)
print('Size', norm.size)
print('Data type', norm.dtype)

[3 0 3 4 4 1 2 3 2 5 5 3 3 1 3 1 4 2 2 5 2 2 3 3 0 3 4 4 4 4 1 3 3 3 3 3 1
 2 2 1 2 2 2 3 4 3 5 3 2 2] 

Number of dim 1
Shape (50,)
Size 50
Data type int64 

[[ 2.15213433 -1.62309421]
 [ 0.02583727  1.15048094]
 [-0.219447    1.47539779]
 [ 0.34993881  0.20444893]
 [ 0.76039088  0.60932799]] 

Number of dim 2
Shape (5, 2)
(2, 5)
Size 10
Data type float64


In [ ]:
# reshaping
print(norm, '\n')
print(norm.reshape(2, 5))

[[ 2.15213433 -1.62309421]
 [ 0.02583727  1.15048094]
 [-0.219447    1.47539779]
 [ 0.34993881  0.20444893]
 [ 0.76039088  0.60932799]] 

[[ 2.15213433 -1.62309421  0.02583727  1.15048094 -0.219447  ]
 [ 1.47539779  0.34993881  0.20444893  0.76039088  0.60932799]]


# Basic Stats Computation

In [ ]:
# Create a 1-d array with 1000 samples drawn from a normal distribution
samples = np.random.normal(0.05, 1, 10000)

# Creat a two-dimensional array with 100 samples drawn from a normal distribution
samples_2d = np.random.normal(0.05, 1, size=(10000, 4))   # 100 rows, 4 columns
samples_2d_ = np.random.normal(0.05, 1, size=(4, 10000))


# Compute mean
print('Mean 1-d', np.mean(samples))
print('Mean 2-d', np.mean(samples_2d, axis = 0))   # across columns
print('Mean 2-d', np.mean(samples_2d_, axis = 1), '\n')  # across rows

# Compute median
print('Median 1-d', np.median(samples))
print('Median 2-d', np.median(samples_2d, axis = 0))   # across columns
print('Median 2-d', np.median(samples_2d_, axis = 1), '\n')  # across rows

# Compute Max and Min
print('Max 1-d', np.max(samples))
print('Max 2-d', np.max(samples_2d, axis = 0))
print('Max 2-d', np.max(samples_2d_, axis = 1))

print('Min 1-d', np.min(samples))
print('Min 2-d', np.min(samples_2d, axis = 0))
print('Min 2-d', np.min(samples_2d_, axis = 1), '\n')

# Compute variance and standard deviation
print('Variance 1-d', np.var(samples))
print('Variance 2-d', np.var(samples_2d, axis = 0))
print('Variance 2-d', np.var(samples_2d_, axis = 1))

print('Std 1-d', np.std(samples))
print('Std 2-d', np.std(samples_2d, axis = 0))
print('Std 2-d', np.std(samples_2d_, axis = 1), '\n')

# Sum
print('Sum 1-d', np.sum(samples))
print('Sum 2-d', np.sum(samples_2d, axis = 0))
print('Sum 2-d', np.sum(samples_2d_, axis = 1), '\n')

# Cumulative sum
print('Cumulative sum 1-d', np.cumsum(samples)[:-5])
print('Cumulative sum 2-d', np.cumsum(samples_2d, axis = 0)[:-5])
print('Cumulative sum 2-d', np.cumsum(samples_2d_, axis = 1)[:-5], '\n')

Mean 1-d 0.040758935380014565
Mean 2-d [0.05197648 0.04973987 0.04281042 0.04297958]
Mean 2-d [0.0518276  0.04492579 0.05103779 0.05183757] 

Median 1-d 0.04255011942044873
Median 2-d [0.04231763 0.06193835 0.03490264 0.03954452]
Median 2-d [0.04440384 0.03563514 0.0568338  0.04494457] 

Max 1-d 3.5673643928682703
Max 2-d [4.15512012 3.74428279 4.50991201 3.73331331]
Max 2-d [3.66976244 3.61417653 3.43542274 5.07000799]
Min 1-d -3.865692796569678
Min 2-d [-3.88147331 -4.12912245 -3.72574164 -4.35563696]
Min 2-d [-3.89653273 -3.80604827 -5.07476745 -3.47621659] 

Variance 1-d 1.0219528892931793
Variance 2-d [1.02776058 0.99358927 1.00883362 1.00423877]
Variance 2-d [0.99150203 0.98712965 0.99482102 0.99909901]
Std 1-d 1.0109168557765664
Std 2-d [1.01378527 0.99678948 1.0044071  1.00211714]
Std 2-d [0.99574195 0.99354399 0.99740715 0.9995494 ] 

Sum 1-d 407.58935380014566
Sum 2-d [519.76481232 497.39866545 428.10415976 429.79575988]
Sum 2-d [518.27599036 449.25787341 510.37790796 518.375

# Array Manipulation
- Broadcasting

In [ ]:
# Generate numbers
a = np.random.randint(1, 10, 5)
a2 = np.random.randint(11, 20, 5)

x  = np.array([a, a2])
b = np.array([2,1]).reshape(2, 1)
print(x)
print(b, '\n')

# multiply add etc
print(a * b)
print(a * b[1])
print(a + b[1])
print(x * b)
print(x * (x + 5), '\n')


# Exponents for each element in array
print(np.exp(x))
print(np.exp(a2), '\n')


# Square root for each element in array
print(np.sqrt(x))
print(np.sqrt(a2), '\n')


# Using np.reshpae for rsshaping
print('Reshaped', np.reshape(x, (5,2)) )
print('Reshaped', np.reshape(x, (2,5)) )

# Using np.resize for reshaping
# Notice the difference to np.reshape
print('Resized', np.resize(x, (6,2)) )
print('Resized', np.resize(x, (2,6)), '\n')


# Round Numbers
rand_num = np.random.randn(10)
print(rand_num)
print(np.round(rand_num, 2))
print(rand_num.round(2), '\n')

# Sort values
# default is wquick sort
rand_norm = np.random.standard_normal(100)
#rand_norm = np.random.shuffle(rand_norm)
print(rand_norm[-10:])
print(np.sort(rand_norm)[-10:])

[[ 3  3  5  4  5]
 [16 14 12 13 12]]
[[2]
 [1]] 

[[ 6  6 10  8 10]
 [ 3  3  5  4  5]]
[3 3 5 4 5]
[4 4 6 5 6]
[[ 6  6 10  8 10]
 [16 14 12 13 12]]
[[ 24  24  50  36  50]
 [336 266 204 234 204]] 

[[2.00855369e+01 2.00855369e+01 1.48413159e+02 5.45981500e+01
  1.48413159e+02]
 [8.88611052e+06 1.20260428e+06 1.62754791e+05 4.42413392e+05
  1.62754791e+05]]
[8886110.52050787 1202604.28416478  162754.791419    442413.39200892
  162754.791419  ] 

[[1.73205081 1.73205081 2.23606798 2.         2.23606798]
 [4.         3.74165739 3.46410162 3.60555128 3.46410162]]
[4.         3.74165739 3.46410162 3.60555128 3.46410162] 

Reshaped [[ 3  3]
 [ 5  4]
 [ 5 16]
 [14 12]
 [13 12]]
Reshaped [[ 3  3  5  4  5]
 [16 14 12 13 12]]
Resized [[ 3  3]
 [ 5  4]
 [ 5 16]
 [14 12]
 [13 12]
 [ 3  3]]
Resized [[ 3  3  5  4  5 16]
 [14 12 13 12  3  3]] 

[ 0.8183102   1.87886823  0.13231386 -0.6888626   0.68007187  0.07188928
 -0.89501832  0.42089028 -1.29280919 -0.15959952]
[ 0.82  1.88  0.13 -0.69  0.68  0.07

In [ ]:
# Stack values
a1 = np.array([[8, 5, 3], [8, 5, 3], [8, 5, 3]])
a2 = np.array([[13, 15, 16], [13, 15, 16], [13, 15, 16]])
a3 = np.array([[27, 21, 29], [27, 21, 29], [27, 21, 29]])

print(np.vstack([a1, a2, a3]))
print(np.hstack([a1, a2, a3]))
print(np.stack([a1, a2, a3]), '\n')

# Column and row stack
print(np.column_stack([a1, a2, a3]))
print(np.row_stack([a1, a2, a3]), '\n')


# Transpose
print(np.transpose(x)) # also print(x.transpose())
print(x.T, '\n')

# Flip
print(np.flip(x))
print(np.flip(x, axis = 0))
print(np.flip(x, axis = 1), '\n')

# Split
print(np.split(x, 1, axis = 0))
print(np.split(x, 1, axis = 1))

[[ 8  5  3]
 [ 8  5  3]
 [ 8  5  3]
 [13 15 16]
 [13 15 16]
 [13 15 16]
 [27 21 29]
 [27 21 29]
 [27 21 29]]
[[ 8  5  3 13 15 16 27 21 29]
 [ 8  5  3 13 15 16 27 21 29]
 [ 8  5  3 13 15 16 27 21 29]]
[[[ 8  5  3]
  [ 8  5  3]
  [ 8  5  3]]

 [[13 15 16]
  [13 15 16]
  [13 15 16]]

 [[27 21 29]
  [27 21 29]
  [27 21 29]]] 

[[ 8  5  3 13 15 16 27 21 29]
 [ 8  5  3 13 15 16 27 21 29]
 [ 8  5  3 13 15 16 27 21 29]]
[[ 8  5  3]
 [ 8  5  3]
 [ 8  5  3]
 [13 15 16]
 [13 15 16]
 [13 15 16]
 [27 21 29]
 [27 21 29]
 [27 21 29]] 

[[ 8 14]
 [ 7 14]
 [ 4 18]
 [ 6 13]
 [ 3 18]]
[[ 8 14]
 [ 7 14]
 [ 4 18]
 [ 6 13]
 [ 3 18]] 

[[18 13 18 14 14]
 [ 3  6  4  7  8]]
[[14 14 18 13 18]
 [ 8  7  4  6  3]]
[[ 3  6  4  7  8]
 [18 13 18 14 14]] 

[array([[ 8,  7,  4,  6,  3],
       [14, 14, 18, 13, 18]])]
[array([[ 8,  7,  4,  6,  3],
       [14, 14, 18, 13, 18]])]


# Bolean Indexing || Array Operations || Array Programming.

In [ ]:
# import numpy
import numpy as np

# create an array
arr = np.arange(2, 20)

# print
print('Lenth', len(arr))
print('Content', arr, '\n')

# subseeting array using array
print(arr[arr % 2 == 0])
print(arr[np.array([5, 4, 1, 6, 15])])

Lenth 18
Content [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[ 2  4  6  8 10 12 14 16 18]
[ 7  6  3  8 17]


In [ ]:
# Vectorized programing: str
# Create random array with  values
numpy = np.array(['Numpy', 'is', 'Magnificietn', 'isnt it', ': Sure!'])

# obtain lenth
vectorized_len = np.vectorize(len)
print(vectorized_len(numpy))
vectorized_len(numpy) < 6

[ 5  2 12  7  7]


array([ True,  True, False, False, False])

In [ ]:
# Vectrozied programming: float
num_array = np.arange(0, 10, 2)
print(num_array)

def divBy2(a):
  return a / 2

vectorized_div = np.vectorize(divBy2)
print(vectorized_div(num_array))

[0 2 4 6 8]
[0. 1. 2. 3. 4.]


In [ ]:
# Create random array with 20 values
randarr= np.random.randint(4, 100, 20)

# print
print('Lenth', len(randarr))
print('Content', randarr, '\n')

# subseeting array using array
print('Greater than 50',  randarr[randarr > 50], '\n')
print('Less than 50',  randarr[randarr < 50], '\n')
print('Greater than 100', randarr[randarr > 100])

print()

# Filter
filt = randarr > 50
print(randarr[filt])

filt_a = np.where(randarr > 50)
print(filt_a, '\n')
print(randarr[np.where(randarr > 50)])

# Creating array of heights: 165 - 185
heights = np.random.uniform(165, 185, 20)
print()
heights

Lenth 20
Content [68 75 62  5 60  6 40 82 65 35 49 45 42 58 33 37 47 13 29 89] 

Greater than 50 [68 75 62 60 82 65 58 89] 

Less than 50 [ 5  6 40 35 49 45 42 33 37 47 13 29] 

Greater than 100 []

[68 75 62 60 82 65 58 89]
(array([ 0,  1,  2,  4,  7,  8, 13, 19]),) 

[68 75 62 60 82 65 58 89]



array([166.18410472, 167.36308416, 175.42379041, 176.84053676,
       173.85756279, 165.02126649, 183.13877529, 168.59946132,
       175.17785177, 183.62970662, 183.77708249, 170.0298424 ,
       176.11792115, 166.95732447, 170.83412315, 171.73695265,
       170.4838487 , 168.22642625, 167.55089191, 169.92084469])

In [ ]:
# return index values
print(np.where(heights > 178), '\n')

# return booleans: T or F
print(np.where(heights > 178, True, False))

# Now create two arrays, for their values to be returned if the above condition holds

x_array = np.arange(0, 20, 1)
y_array = np.arange(100, 120, 1)

print(x_array, '\n')
print(y_array)
print()

np.where(heights > 170, y_array, x_array)

(array([ 6,  9, 10]),) 

[False False False False False False  True False False  True  True False
 False False False False False False False False]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]



array([  0,   1, 102, 103, 104,   5, 106,   7, 108, 109, 110, 111, 112,
        13, 114, 115, 116,  17,  18,  19])

#

In [ ]:
# Build hypothetical close prices
# Close prices Year 1.
cls_prices = np.random.randint(100, 125, 20)

# Close prices Year 2.
close_prices = np.random.uniform(100, 125, 20)
close_prices

array([101.73953637, 102.36510065, 117.77232502, 118.41740719,
       104.56664698, 115.20275214, 106.50597039, 117.84348301,
       124.2885547 , 112.51272184, 117.30529316, 117.07439787,
       107.84477522, 119.89638079, 113.07214008, 105.38693425,
       102.99235422, 113.16851228, 107.02176066, 109.6053388 ])

In [ ]:
# Generate signals based on average close prices for years 1.
avg_price = np.mean(cls_prices)
print(avg_price)

signal = np.where(close_prices > avg_price, 1, 0)
print(signal)

108.15
[0 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1]


# Iterations

In [ ]:
# Looping across 1-d array
# until before last 15 values
for _ in signal[:-15]:
    print(_)

# # Looping across 2-d array
# combine two arrays
comb_array = np.array([signal[-5:], close_prices[-5:]])
print(comb_array)

for arr in comb_array:
    for ele in arr:
        print(ele)

# Also n.diter can be used irrespective of dimensions
for ele in np.nditer(signal[:5]):
    print(ele)
for ele in np.nditer(comb_array):
    print(ele)

0
0
1
1
0
[[  0.           0.           1.           0.           1.        ]
 [105.38693425 102.99235422 113.16851228 107.02176066 109.6053388 ]]
0.0
0.0
1.0
0.0
1.0
105.38693424500275
102.99235422242023
113.16851227590077
107.02176065558217
109.60533879509
0
0
1
1
0
0.0
0.0
1.0
0.0
1.0
105.38693424500275
102.99235422242023
113.16851227590077
107.02176065558217
109.60533879509


In [ ]:
# Checking documentation
#help(np.unique)
#help(np.random.randint)
#help(np.concatenate)
#help(np.flatten)
#help(np.ravel)
#help(np.reshape)
#help(np.insert)
#help(np.append)
#help(np.delete)
#help(np.diag)
#help(np.reshape)
# etc,.
help(np.delete)

Help on _ArrayFunctionDispatcher in module numpy:

delete(arr, obj, axis=None)
    Return a new array with sub-arrays along an axis deleted. For a one
    dimensional array, this returns those entries not returned by
    `arr[obj]`.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : slice, int or array of ints
        Indicate indices of sub-arrays to remove along the specified axis.
    
        .. versionchanged:: 1.19.0
            Boolean indices are now treated as a mask of elements to remove,
            rather than being cast to the integers 0 and 1.
    
    axis : int, optional
        The axis along which to delete the subarray defined by `obj`.
        If `axis` is None, `obj` is applied to the flattened array.
    
    Returns
    -------
    out : ndarray
        A copy of `arr` with the elements specified by `obj` removed. Note
        that `delete` does not occur in-place. If `axis` is None, `out` is
        a flattened array.
    
   

In [ ]:
# The End!!